name: Build

on:
    push:
        branches:
            - 'qa'
            # - 'master'
    # release:
    #     types: [published]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macOS-latest, ubuntu-latest, windows-latest]

        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4

            - name: Build
              run: |
                  npm install
                  npm run make
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SECRET_MESSAGE: ${{ secrets.SECRET_MESSAGE }}
                  SECRET_KEY: ${{ secrets.SECRET_KEY }}
                  API_URL: ${{ secrets.API_URL }}

            - name: Release
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  draft: true
                  files: |
                      out/**/*.deb
                      out/**/*.dmg
                      out/**/*Setup*.exe
                      out/**/*.rpm
                      out/**/*.zip
                      out/**/*.nupkg
                      out/**/RELEASES
