name: Build

on:
    push:
        branches:
            - 'qa'
            # - 'master'
    # release:
    #     types: [published]

jobs:
    build-linux:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4

            - name: Build for Linux
              run: |
                  npm install
                  npm run make

            - name: Release
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  draft: true
                  files: |
                      out/**/*.deb
                      out/**/*.dmg
                      out/**/*setup*.exe
                      out/**/*.nupkg
                      out/**/*.rpm
                      out/**/*.zip
                      out/**/RELEASES

                      # - name: Use the Upload Artifact GitHub Action
                      #   uses: actions/upload-artifact@v2
                      #   with:
                      #       name: ouput-test
                      #       path: out/make

    build-mac:
        runs-on: macos-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4

            - name: Build for Mac
              run: |
                  npm install
                  npm run make

            - name: Release
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  draft: true
                  files: |
                      out/**/*.deb
                      out/**/*.dmg
                      out/**/*setup*.exe
                      out/**/*.nupkg
                      out/**/*.rpm
                      out/**/*.zip
                      out/**/RELEASES

                      # - name: Use the Upload Artifact GitHub Action
                      #   uses: actions/upload-artifact@v2
                      #   with:
                      #       name: ouput-test
                      #       path: out/make

    build-windows:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4

            - name: Build for Windows
              run: |
                  npm install
                  npm run make

            - name: Release
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  draft: true
                  files: |
                      out/**/*.deb
                      out/**/*.dmg
                      out/**/*setup*.exe
                      out/**/*.nupkg
                      out/**/*.rpm
                      out/**/*.zip
                      out/**/RELEASES

                      # - name: Use the Upload Artifact GitHub Action
                      #   uses: actions/upload-artifact@v2
                      #   with:
                      #       name: ouput-test
                      #       path: out/make
