name: Build Linux

on:
    # push:
    #     branches:
    #         - 'master'
    release:
        types: [published]

jobs:
    build-linux:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo
              uses: actions/checkout@v2.3.4

            - name: Build for Linux
              run: |
                  npm install
                  npm run make

            - name: Use the Upload Artifact GitHub Action
              uses: actions/upload-artifact@v2
              with:
                  name: ouput-test
                  path: out/make

    build-mac:
        runs-on: macos-latest

        steps:
            - name: checkout repo
              uses: actions/checkout@v2.3.4

            - name: Build for Linux
              run: |
                  npm install
                  npm run make

            - name: Use the Upload Artifact GitHub Action
              uses: actions/upload-artifact@v2
              with:
                  name: ouput-test
                  path: out/make

    build-windows:
        runs-on: windows-latest

        steps:
            - name: checkout repo
              uses: actions/checkout@v2.3.4

            - name: Build for Linux
              run: |
                  npm install
                  npm run make

            - name: Use the Upload Artifact GitHub Action
              uses: actions/upload-artifact@v2
              with:
                  name: ouput-test
                  path: out/make
